AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Secure Volunteer Matching App - Core Infrastructure

Globals:
  Function:
    Timeout: 10
    MemorySize: 256

Parameters:
  StageName:
    Type: String
    Default: prod

Resources:
  MatchingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-MatchingTable"

      # 1 RCU / 1 WCU to stay within Free Tier
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S

      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          # 1 RCU / 1 WCU to stay within the Free Tier
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

  VolunteerMatchingApi:
    Type: AWS::Serverless::Api
    DependsOn: VolunteerUserPool
    Properties:
      StageName: !Ref StageName
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'GET,POST,OPTIONS,PUT,DELETE'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt VolunteerUserPool.Arn

  # Lambda Function placeholder
  GraphQLFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: python3.11
      CodeUri: backend/
      Environment:
        Variables:
          MATCHING_TABLE_NAME: !Ref MatchingTable
          STAGE: prod
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref MatchingTable
  GraphqlResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt VolunteerMatchingApi.RootResourceId
      PathPart: graphql
      RestApiId: !Ref VolunteerMatchingApi

  GraphqlPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !GetAtt VolunteerMatchingApi.Authorizers.CognitoAuthorizer
      HttpMethod: POST
      ResourceId: !Ref GraphqlResource
      RestApiId: !Ref VolunteerMatchingApi

      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GraphQLFunction.Arn}/invocations"
        PassthroughBehavior: WHEN_NO_MATCH

        RequestTemplates:
          application/json: |
            #set($context.authorizer.claims = $context.authorizer.claims)
            {
              "body": $input.json('$'),
              "method": "$context.httpMethod",
              "headers": {
                #foreach($header in $input.params().header.keySet())
                  "$header": "$util.escapeJavaScript($input.params().header.get($header))" #if($foreach.hasNext),#end
                #end
              },
              "path": "$context.resourcePath",
              "requestContext": {
                "authorizer": {
                  "claims": $context.authorizer.claims
                }
              }
            }

      MethodResponses:
        - StatusCode: "200"

  GraphqlOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: OPTIONS
      ResourceId: !Ref GraphqlResource
      RestApiId: !Ref VolunteerMatchingApi

      Integration:
        Type: MOCK
        IntegrationHttpMethod: POST
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        PassthroughBehavior: WHEN_NO_MATCH

        IntegrationResponses:
          - StatusCode: "200"
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS,PUT,DELETE'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ""

      MethodResponses:
        - StatusCode: "200"
          ResponseModels: {}
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  GraphqlFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt GraphQLFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${VolunteerMatchingApi}/*/*"

  # Cognito pool for auth
  VolunteerUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: VolunteerAppUserPool
      # Enforce strong password policies
      Policies:
        PasswordPolicy:
          MinimumLength: 12
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      AutoVerifiedAttributes:
        - email

  VolunteerUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: WebClient
      UserPoolId: !Ref VolunteerUserPool
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      # Required for static web/mobile clients
      GenerateSecret: false

Outputs:
  GraphQLApiId:
    Value: !Ref VolunteerMatchingApi
    Description: "API Gateway ID"
  GraphQLApiEndpoint:
    Value: !Sub "https://${VolunteerMatchingApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/graphql"
    Export:
      Name: !Sub "${AWS::StackName}-GraphQLEndpoint"
    Description: "GraphQL API endpoint URL"
  VolunteerUserPoolId:
    Value: !Ref VolunteerUserPool
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolId"
    Description: "Cognito user pool ID"
  VolunteerUserPoolClientId:
    Value: !Ref VolunteerUserPoolClient
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolClientId"
    Description: "Cognito user pool client ID"
